services:
  web-store:
    platform: linux/amd64
    build: .
    image: ${REGISTRY}web-etcstore
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - "FLAG=ctfcup{example}"