services:
  likvidirovan:
    build: .
    platform: linux/amd64
    image: ${REGISTRY}medium-likvidirovan
    mem_limit: 256M
    memswap_limit: 256M
    restart: unless-stopped
    stop_grace_period: 3s
    ports:
      - "18333:31337"
