services:
  olymp:
    build: .
    platform: linux/amd64
    image: "${REGISTRY}pwn-olymp"
    ports:
      - "1717:1717"
    restart: unless-stopped
    cpus: 1
    pids_limit: 64
    mem_limit: 512m
    environment:
      - FLAG=ctfcup{test_flag}
